apiVersion: v1
name: elbv2-chart
description: A Helm chart for the ACK service controller for Elastic Load Balancing (ELB)
version: 1.1.3
appVersion: 1.1.3
home: https://github.com/aws-controllers-k8s/elbv2-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/elbv2-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ELB Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/elbv2-maintainer
keywords:
  - aws
  - kubernetes
  - elbv2
